version: "3.9"
services:
  thebot:
    build: .
    environment:
      - BOT_DEBUG_ENVIRONMENT=0
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_COMMAND_PREFIX=${BOT_COMMAND_PREFIX}
      - BOT_DB_HOST=${BOT_DB_HOST}
      - BOT_DB_USERNAME=${BOT_DB_USERNAME}
      - BOT_DB_PASSWORD=${BOT_DB_PASSWORD}
