version: "3.9"
services:
  thebot:
    image: br1armabot:master
    restart: always
  bot_db:
    image: mariadb
    restart: always
    volumes:
      - '/etc/br1bot/database/:/var/lib/mysql'
