version: "3.9"
services:
  thebot:
    image: br1armabot:master
    restart: always
  bot_db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: changethis
