# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Verify Application

# This should only execute on direct pushes to master, or a merge to master
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - closed
    branches:
      - master

permissions:
  contents: read

jobs:
  docker-build:
    runs-on: "ubuntu-latest"

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    -
      name: Build image
      run: |
        docker build -t br1armabot:${GITHUB_REF##*/} .
